package org.sarge.textrpg.entity;

import org.sarge.textrpg.util.ArgumentFormatter;
import org.sarge.textrpg.util.Description;
import org.sarge.textrpg.util.Percentile;

/**
 * Entity that can be ridden.
 * @author Sarge
 * TODO - saddles, inventory? speed? movement cost modifier, ride difficulty?
 */
public class Mount extends Entity implements Follower {
	private final FollowerModel follower = new FollowerModel();

	/**
	 * Constructor.
	 * @param race Mount race
	 */
	public Mount(Race race) {
		super(new DefaultEntityDescriptor(race, null), null); // TODO
	}

	@Override
	public FollowerModel follower() {
		return follower;
	}

	/**
	 * @return Movement cost modifiers for actors riding this mount
	 */
	public float modifier() {
		// TODO
		return 0.1f;
	}

	/**
	 * @return Noise generated by this mount when moving
	 */
	public Percentile noise() {
		return descriptor().race().gear().noise();
	}

	@Override
	public Description describe(ArgumentFormatter.Registry formatters) {
		// TODO - tired
		return super.describe(formatters);
	}

	@Override
	protected void destroy() {
		Follower.clear(this);
		super.destroy();
	}
}
